# Generated by Django 2.1.3 on 2020-07-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetflixApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=500)),
                ('avg_rating', models.FloatField()),
                ('runtime', models.CharField(max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
