# Generated by Django 3.0.8 on 2020-07-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetflixApp', '0002_auto_20200719_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
