# Generated by Django 3.0.8 on 2020-07-20 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NetflixApp', '0003_auto_20200720_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=500)),
                ('avg_rating', models.FloatField()),
                ('runtime', models.CharField(max_length=10)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
