# Generated by Django 3.0.8 on 2020-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetflixApp', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmovie',
            name='avg_rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='recommendedmovie',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
