# Generated by Django 3.0.8 on 2020-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetflixApp', '0006_auto_20200724_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmovie',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
